### ISSUE TITLE
documentation help needed ?

### ISSUE THREAD

**Issue by crognon** [remy/jace#1]
Hi, is ther any doc on this ?

if you need help you could provide a simple text file I could use it to document your work :)

Thanks
Cyril

**Comment by remy** [comment]
There's some on jqterm.com - which is where this currently resides.

**Comment by crognon** [comment]
jqterm seems not to process the jq filters anymor

![image](https://user-images.githubusercontent.com/3236191/42085868-e6299a4a-7b91-11e8-9ed0-ab9f19403877.png)

**Comment by crognon** [comment]
also I do not see any hints nor documentation on the page. What could I be missing ?

thanks
Cyril

**Comment by remy** [comment]
Sorry, late to replying to this.

If you use the keys `ctrl + shift + ?` it'll show you some help. 

The big obvious problem is that the initial content isn't queryable - which I know is confusing! I'll fix that.
