### ISSUE TITLE
Where is the data stored?

### ISSUE THREAD

**Issue by borekb** [remy/jace#10]
Hi, a really neat service! I'm wondering, where is the data stored / persisted? Some sort of database? Is it encrypted or plain text? Thanks!

**Comment by remy** [comment]
It's in a private gist. Only you know the URL to the gist, and unless you
publish these yourself, the URLs are private.

**Comment by borekb** [comment]
I'm not sure which Gist. I just visited `jqterm.com`, entered a JSON and a query and got a URL like this back:

`https://jqterm.com/2d6d6....?query=...`

This URL worked also in a different browser so I guess my JSON is persisted somewhere. I didn't authenticate with my GitHub account so there is no new Gist in my account (obviously).

**Comment by remy** [comment]
Your second comment doesn't ask a question. 

I've said that the source data is persisted to a gist - that is on gist.github.com. It uses a single account and it's all marked as private.

*Again* if you share the URL (as you did between browsers) then the URL will work, otherwise it remains unpublished and private.

This is not stored under your account, it's stored under a single private account. 

If you have technical questions feel free to view the source.

**Comment by borekb** [comment]
Thanks for the clarification.

Would you consider putting this functionality behind an explicit action like a "share" button, or at least making it clear that anything pasted to `jqterm.com` is uploaded to a 3rd party service in a plain text format? I understand that pasting text into any website is inherently risky but most online playgrounds / editors don't share user data by default, or at least have privacy policies that explain how user data is treated and which other third parties have access to them.

(To be clear, technically, I understand that it is unlikely / close to impossible to guess the Gist's ID and hence "leak" user data.)

**Comment by remy** [comment]
The share functionality is the URL bar in the browser. The point where a user pastes data into jqterm it is *stored* in a gist, not shared.

**Comment by borekb** [comment]
You're right, my sentence _"most online playgrounds / editors don't share user data by default"_ should have used the word _store_ instead of _share_. Other than that, what do you think about making this more explicit / user-controlled? My data ended up on GitHub's servers as plain text, accessible via URL. This was sort of unexpected.

**Comment by remy** [comment]
Can you access the raw form data via a URL? ie. On GitHub

**Comment by borekb** [comment]
Yes, I can. I see my JSON on `gist.github.com` and there's no way for me to delete it, right?

**Comment by remy** [comment]
That's correct. There's no way to delete it. If the URL is never shared, it's never available to anyone but the owner.

**Comment by remy** [comment]
So, the short version of this is: the share feature is the URL bar of the browser. 

I'm not adding UI.

No one should be pasting sensitive data into any web site, full stop.

Data is typically stored in a 3rd party, be it aws, azure, mlab and so on. Gists are just that. 

I don't plan to add unneeded text to explain where content is stored, I've been though this loop before and it's a waste of time, particularly for a mini service like this. 

If you're not comfortable with that (and the same applies for anyone else), I've been good enough to provide full source available for either private hosting or changes to suit one's own needs. 

I hope this clarifies my position. Cheers.
