### ISSUE TITLE
walk/1 function not working.

### ISSUE THREAD

**Issue by Chieftl** [remy/jace#4]
walk function not working.
Please update jq to new version.
```jq: error: walk/1 is not defined at <top-level>```

**Comment by remy** [comment]
No, walk was removed from jq, you need to manually define it yourself.

You can see it in use [here](https://jqterm.com/5720a29ba9992666879ce0f915ab2208?query=%23%20walk%20was%20removed%20from%20jq%401.5%0Adef%20walk%28f%29%3A%0A%20%20.%20as%20%24in%0A%20%20%7C%20if%20type%20%3D%3D%20"object"%20then%0A%20%20%20%20%20%20reduce%20keys%5B%5D%20as%20%24key%0A%20%20%20%20%20%20%20%20%28%20%7B%7D%3B%20.%20%2B%20%7B%20%28%24key%29%3A%20%20%28%24in%5B%24key%5D%20%7C%20walk%28f%29%29%20%7D%20%29%20%7C%20f%0A%20%20elif%20type%20%3D%3D%20"array"%20then%20map%28%20walk%28f%29%20%29%20%7C%20f%0A%20%20else%20f%0A%20%20end%3B%0A%0Awalk%28if%20type%20%3D%3D%20"object"%20then%20.%20%7C%20del%28.email%29%20else%20.%20end%29)

**Comment by Chieftl** [comment]
But "walk" comes back in v1.6
https://stedolan.github.io/jq/manual/v1.6/
https://raw.githubusercontent.com/stedolan/jq/master/NEWS

**Comment by remy** [comment]
Sod, good shout!

I'm upgrading and deploying - will post back here when live 👍

**Comment by remy** [comment]
Wow. That build went super super wrong! All live now though 👍 	

[Example](https://jqterm.com/5720a29ba9992666879ce0f915ab2208?query=walk%28if%20type%20%3D%3D%20%22object%22%20then%20.%20%7C%20del%28.email%29%20else%20.%20end%29)
