### ISSUE TITLE
Is "debug" function supported?

### ISSUE THREAD

**Issue by Chieftl** [remy/jace#5]
I am trying to debug jq queries, but "debug" function don't show any info.
Example:
https://jqterm.com/1cc43afabaef5dc44a7d718618bf5767?query=.%20%7C%20debug
For comparison:
https://jqplay.org/s/Zc1oVLSFFS

**Comment by remy** [comment]
Ah, it would seem not. jqterm only captures STDOUT and not STDERR (or it's ignoring it in this case).

I'll have to add that as a feature, good catch 👍
